server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      url: redis://:${REDIS_PASSWORD:}@${REDIS_HOST:localhost}:${REDIS_PORT:6379}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # 로컬에서 DB 확인용 서버 가부화 감소
      maximum-pool-size: 2

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_EXPIRATION:604800000}
