// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKDTdsAw8tCRbYH4rj4tY1Frzf3NCVJVg',
    appId: '1:686450725098:web:1c968b8b3b4314761c0793',
    messagingSenderId: '686450725098',
    projectId: 'noill-app',
    authDomain: 'noill-app.firebaseapp.com',
    storageBucket: 'noill-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8bESEd_tAqIgW9fTxQIxmMGZfuPIyEA',
    appId: '1:686450725098:android:6ce26564eecb2b3b1c0793',
    messagingSenderId: '686450725098',
    projectId: 'noill-app',
    storageBucket: 'noill-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVay1DYW7kx5o2KJBDazbGwHTZas9kdM',
    appId: '1:686450725098:ios:420a3036e9c0f37a1c0793',
    messagingSenderId: '686450725098',
    projectId: 'noill-app',
    storageBucket: 'noill-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKDTdsAw8tCRbYH4rj4tY1Frzf3NCVJVg',
    appId: '1:686450725098:web:4909a5b7824536781c0793',
    messagingSenderId: '686450725098',
    projectId: 'noill-app',
    authDomain: 'noill-app.firebaseapp.com',
    storageBucket: 'noill-app.firebasestorage.app',
  );
}
